### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by zopar** [tmtk75/vagrant-prometheus-sample#3]
To avoid the error during server provision:
TASK [command] *****************************************************************
failed: [server] (item=fluent-plugin-prometheus) => {"changed": true, "cmd": "/usr/sbin/td-agent-gem install fluent-plugin-prometheus" ...

I opened a pull request, #2  we need dev tools installation with yum

**Comment by tmtk75** [comment]
I've merged #2.
